source nvm to make nvm command available

diff --git a/bin/install_requirements b/bin/install_requirements
--- a/bin/install_requirements
+++ b/bin/install_requirements
@@ -4,7 +4,8 @@ RED='\033[0;31m'
 PURPLE='\033[0;35m'
 RESET='\033[0m'
 script="$(basename "$0")"
-SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"
+script_dir="$( cd "$( dirname "$0" )" && pwd )"
+requirements_dir="$( dirname "$script_dir" )/requirements"
 
 log() {
   echo -e "${PURPLE}${script}:${RESET} $1"
@@ -15,7 +16,7 @@ fail() {
   exit 1
 }
 
-cd $SCRIPT_DIR
+cd $script_dir
 
 log "Removing rvm if you have it..."
 read -p "Press enter to continue."
@@ -26,7 +27,7 @@ if which rvm > /dev/null; then
   log "rvm imploded."
 fi
 
-cd $SCRIPT_DIR
+cd $script_dir
 
 log "Switch to OS specific script..."
 read -p "Press enter to continue."
@@ -53,14 +54,13 @@ esac
 log "Switching back to non-OS specific script..."
 log "Installing Ruby..."
 read -p "Press enter to continue."
+cd $requirements_dir
 
-echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc || fail "unable to add PATH variable"
-echo 'eval "$(rbenv init -)"' >> ~/.bashrc || fail "could not activate rbenv"
 if rbenv global "$RUBY_VERSION"; then
   log "Ruby v$RUBY_VERSION already installed."
 else
-  log "Upgrading rbenv..."
-
+  log "activating rbenv..."
+  eval "$(rbenv init -)" || fail "could not activate rbenv"
   log "Installing Ruby v$RUBY_VERSION..."
   rbenv install "$RUBY_VERSION"
   log "Ruby v$RUBY_VERSION installed."
@@ -68,7 +68,7 @@ fi
 rbenv global "$RUBY_VERSION"
 rbenv rehash
 
-log "Ruby v${RUBY_VERSION} set as default version."
+log "Ruby v$RUBY_VERSION set as default version."
 log "Installing bundler and gems..."
 read -p "Press enter to continue."
 
diff --git a/bin/install_requirements_linux b/bin/install_requirements_linux
--- a/bin/install_requirements_linux
+++ b/bin/install_requirements_linux
@@ -17,9 +17,6 @@ fail() {
   exit 1
 }
 
-cd "$( dirname "$0" )/../requirements"
-requirements_dir="$( pwd )"
-
 clear
 log "Linux Development Setup"
 log "Each group of packages will be install one at a time. Follow the prompts to continue."
@@ -70,13 +67,26 @@ else
 fi
 
 log "Postgresql install complete..."
+log "Installing Rbenv next..."
+read -p "Press enter to continue"
+
+if which rbenv > /dev/null; then
+  log "rbenv already installed"
+else
+  git clone https://github.com/rbenv/rbenv.git ~/.rbenv
+  echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc || fail "unable to add PATH variable"
+  echo 'eval "$(rbenv init -)"' >> ~/.bashrc || fail "could not activate rbenv"
+  source ~/.bashrc
+  git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
+fi
+
+log "Rbenv installed"
 log "Installing NVM, Node and NPM next..."
 read -p "Press enter to continue"
 clear
 
 ##NVM (node version manager), Node, and NPM
 
-[[ -n "$NVM_DIR" ]] || export NVM_DIR="$HOME/.nvm"
 if [[ -d "$NVM_DIR" ]]; then
   log "NVM already installed."
 else
@@ -88,8 +98,9 @@ fi
 if nvm ls "$NODE_VERSION" > /dev/null; then
   log "Node v$NODE_VERSION already installed."
 else
+  source ~/.nvm/nvm.sh
   nvm install "$NODE_VERSION"
-  nvm use node
+  nvm use node "$NODE_VERSION"
   npm install -g npm
 fi
 
